### PR TITLE
Api endpoints

### PR DESCRIPTION
**Pull request by MKCMMSK**
Split work with Eli, these are the basic routes for vendors, customer-order, vendor-order.

### CODE REVIEW

**Review by andydlindsay — COMMENTED** [review]
Does this have things in common with #17 and #18? Seems like a lot of crossover.

**Comment by ElectricMolasses** [comment]
It looks like this branch should have actually started at commit 468bbe4.
We pulled my changes down to theirs briefly, so that they could match the file structure I was building, and then must have forgotten to move to a fresh branch before actually doing work.

**Comment by MKCMMSK** [comment]
That is exactly what happened. The only real changes from this branch are within the routes.go file.

**Comment by andydlindsay** [comment]
> That is exactly what happened. The only real changes from this branch are within the routes.go file.

Okay. That should resolve itself then when the first PR is merged into master. PR's only look at what is different from master.

**Pull request merged**
